name: Deploy package to GitHub Packages

on:
  push:
    branches: [ "main", "develop-*" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Deploy package
      run: mvn --batch-mode clean deploy --file pom.xml --settings .github/workflows/deploy_settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
